M48
; DRILL file {KiCad 9.0.7} date 2026-03-10T14:54:44+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-10T14:54:44+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X94.0Y-47.0
X94.0Y-136.0
X221.0Y-47.0
X221.0Y-136.0
M30
